name: Build & Push Spring Boot Docker

on:
  push:
    branches: ["production"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build JAR
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Login Docker Hub
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-app .

      # 6. Push lên Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-app